### PR TITLE
Rescript jest

### PR DESCRIPTION
**Pull request by sacarr**
@glennsl I noticed one more typo this morning after you merged 97.

BTW, I don't see 0.8.0 showing up in the releases list on GitHub.  It's also not available on [npmjs.com](https://npmjs.com).  I don't see any actions associated with the repo.  Do you manage npm releases manually?

### CODE REVIEW

**Review by glennsl — COMMENTED** [review]
Thanks! But since this includes a couple of duplicate commits and would have had to undergo a potentially messy rebase, I just fixed it myself in https://github.com/glennsl/rescript-jest/commit/f8e9aaaf668957dfa020d7bce69f6af54042de72.

**Comment by glennsl** [comment]
> BTW, I don't see 0.8.0 showing up in the releases list on GitHub. It's also not available on npmjs.com. I don't see any actions associated with the repo. Do you manage npm releases manually?

Oh, forgot about this. I use `np`, and it seemed to succeed, but maybe it failed in some stealthier than usual way. I'll try again.

**Comment by glennsl** [comment]
There, now it's released. Thanks for the heads up!

**Comment by sacarr** [comment]
Thanks Glenn, 
I see it now.  Thanks also for fixing the one last PR.

**Pull request closed without merging**
